

- path: /login
  component: ./UserLogin/index
- path: /register
  component: ./UserRegister/index
- path: /topics
  routes:
    - path: /topics/topic-edit
      component: ./topic/writeTopic
    - path: /topics/:id
      component: ./topic/detail
- path: /
  component: '../layouts/index'
  routes:
    - path: /
      component: ./index
    - path: /topic/:id
      component: ./topic/detail
    - path: /explore
      component: ./explore/index
    - path: /register
    - path: /account/center
      component: ./account/center
    - component: Exception404

