

- path: /
  name: layout
  component: '../layouts/index'
  routes:
    - path: /
      name: homepage
      component: ./index
    - path: /blogs
      name: blogs
      component: ./blogs/index
    - path: /blogs/:id
      name: blog-detail
      component: ./blogs/detail
    - path: /people
      name: people
      component: ./blogs/index
    - path: /people/:id
      name: people-detail
      component: ./people/detail
    - path: /questions
      name: questions
      component: ./questions/index
    - path: /questions/:id
      name: questions-detail
      component: ./questions/detail
    - path: /login
      name: login
      component: ./UserLogin/index
    - path: /register
      name: register
      component: ./UserRegister/index
    - component: Exception404

