

- path: /
  name: layout
  component: '../layouts/index'
  routes:
    - path: /
      name: homepage
      component: ./index
    - path: /topics
      name: topics
      component: ./topic/index
    - path: /explore
      name: explore
      component: ./explore/index
    - path: /topic/:id
      name: topic-detail
      component: ./topic/detail
    - path: /login
      name: login
      component: ./UserLogin/index
    - path: /register
      name: register
    - path: /account/center
      name: account-center
      component: ./account/center
    - path: /register
      name: register
      component: ./UserRegister/index
    - component: Exception404

