

- path: /
  name: layout
  component: '../layouts/index'
  routes:
    - path: /
      name: homepage
      component: ./index
    - path: /blogs
      name: blogs
      component: ./blogs/index
    - path: /blogs/:id
      name: blog-detail
      component: ./blogs/detail
    - component: '404'
